main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("about/", views.about, name="about"),
    path("records/", views.record_index, name="record-index"),
    path("records/<int:record_id>/", views.record_detail, name="record-detail"),
    path("records/create", views.RecordCreate.as_view(), name="record-create"),
    path("records/<int:pk>/update/",
         views.RecordUpdate.as_view(), name="record-update"),
    path("records/<int:pk>/delete/",
         views.RecordDelete.as_view(), name="record-delete"),
    path("records/<int:record_id>/add-track/",
         views.add_track, name="add-track"),
    path('accounts/signup/', views.signup, name='signup'),
]

vinylcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Record(models.Model):
  title = models.CharField()
  artist = models.CharField()
  release_date = models.DateField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("record-detail", kwargs={"record_id": self.id})


class Track(models.Model):
  track_no = models.IntegerField()
  title = models.CharField()
  duration = models.DurationField()

  record = models.ForeignKey(Record, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

main_app/forms.py
from django import forms
from .models import Track, Record


class RecordForm(forms.ModelForm):
  class Meta:
    model = Record
    fields = ['title', 'artist', 'release_date']
    widgets = {'release_date': forms.DateInput(
        format=('%Y-%m-%d'), attrs={
            'placeholder': 'Select a date', 'type': 'date'
        }
    ),
    }


class TrackForm(forms.ModelForm):
  class Meta:
    model = Track
    fields = ['track_no', 'title', 'duration']

main_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from .models import Record, Track
from .forms import TrackForm, RecordForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class RecordCreate(LoginRequiredMixin, CreateView):
  model = Record
  form_class = RecordForm

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class RecordUpdate(LoginRequiredMixin, UpdateView):
  model = Record
  fields = "__all__"


class RecordDelete(LoginRequiredMixin, DeleteView):
  model = Record
  success_url = "/records/"


class Home(LoginView):
  template_name = 'home.html'


def about(request):
  return render(request, "about.html")


@login_required
def record_index(request):
  records = Record.objects.filter(user=request.user)
  return render(request, "records/index.html", {"records": records})


@login_required
def record_detail(request, record_id):
  record = Record.objects.get(id=record_id)
  track_form = TrackForm()
  return render(request, "records/detail.html", {"record": record, "track_form": track_form})


@login_required
def add_track(request, record_id):
  form = TrackForm(request.POST)
  if form.is_valid():
    new_track = form.save(commit=False)
    new_track.record_id = record_id
    new_track.save()
  return redirect("record-detail", record_id=record_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in
      login(request, user)
      return redirect('record-index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)
  # Same as:
  # return render(
  #     request,
  #     'signup.html',
  #     {'form': form, 'error_message': error_message}
  # )

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}
<h1>About the Vinyl Collector</h1>
<hr />
<p class="page-content">I like music</p>
{% endblock %}
<p></p>

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			href="https://fonts.googleapis.com/css2?family=Rock+Salt&display=swap"
			rel="stylesheet" />
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.cyan.min.css" />
		<link rel="stylesheet" href="{% static "css/base.css" %}">
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <script src="{% static "js/modal.js" %}" defer></script>
		<title>Vinyl Collector</title>
		{% block head %} {% endblock %}
	</head>
	<body>
		<header class="container">
			<nav>
				<ul>
					<li>
						<a href="/">
							<img class="nav-logo" src="{% static "images/vinyl-record.png" %}"
							alt="Vinyl Collector Logo" />
						</a>
					</li>
				</ul>
				<ul>
          {% if user.is_authenticated %}
					<li><a href="{% url 'record-index'%}">All Records</a></li>
					<li><a href="{% url 'record-create' %}">Add Record</a></li>
					<li><a href="{% url 'about'%}">About</a></li>
          <li>
            <form id="logout-form" method="post" action="{% url "logout" %}">
              {% csrf_token %}
              <button role="button" type="submit">Log Out</button>
            </form>
          </li>
          {% else %}
					<li><a href="{% url 'about'%}">About</a></li>
					<li><a role="button" href="{% url 'home'%}">Login</a></li>
          <li><a role="button" href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
				</ul>
			</nav>
		</header>
		<main class="container">{% block content %} {% endblock %}</main>
	</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% load static %} {% block head %} {% endblock %}
{%block content %}
<article>
	<section>
		<article class="landing-container">
			<img class='landing-logo' src="{% static "images/vinyl-record.png" %}"
			alt="">
			<h1 class="rock-salt-regular">Vinyl Collector</h1>
		</article>
	</section>
	{% if not user.is_authenticated %}
	<section>
		<form action="{% url 'home' %}" method="post" class="login">
			<h1>Login</h1>
			{% csrf_token %} {{ form.as_p }}
			<input type="hidden" name="next" value="{{ next }}" />
			<button type="submit" class="btn submit">Login</button>
		</form>
	</section>
</article>
{% endif %} {% endblock %}

main_app/templates/main_app/record_confirm_delete.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="page-header">
	<h1>Delete record?</h1>
</div>

<h2>Are you sure you want to delete {{ record.title }}?</h2>

<form action="" method="post" class="form">
	{% csrf_token %}
	<a href="{% url 'record-detail' record.id %}" class="btn secondary">Cancel</a>
	<button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

main_app/templates/main_app/record_form.html
{% extends "base.html" %} {% load static %} {% block head %} {% endblock head %}
{% block content %}
<div class="page-header">
	{% if record %}
	<h1>Edit {{record.title}}</h1>
	{% else %}
	<h1>Add a Record</h1>
	{% endif %}
</div>
<form action="" method="post" class="form-container">
	{% csrf_token %}
	<table>
		{{form.as_table}}
	</table>
	<button type="submit" class="btn" submit>Submit!</button>
</form>
{% endblock content %}

main_app/templates/records/detail.html
{% extends 'base.html' %} {% load static %} {% block head %} {% endblock %}
{%block content %}
<section class="record-container">
	<article class="record-details">
		<h1 class="rock-salt-regular">{{record.title}}</h1>
		<h2>{{record.artist}}</h2>
		<h3>{{record.release_date}}</h3>
		<div class="record-actions">
			<a href="{% url 'record-update' record.id %}" class="btn warn">Edit</a>
			<a href="{% url 'record-delete' record.id %}" class="btn danger"
				>Delete</a
			>
    </article>
	</div>
	<dialog id="track-add-form">
		<article>
			<form
				action="{% url 'add-track' record.id %}"
				method="post"
				class="subsection-content"
				autocomplete="off">
				<h3>Add A Track</h3>
				{% csrf_token %} {{track_form.as_table}}
				<button type="submit" class="btn submit">Add track</button>
			</form>
		</article>
	</dialog>
	<article class="track-container">
		<h2>Track Listing</h2>
		{% if record.track_set.all.count %}
		<table>
			<thead>
				<tr>
					<th>Track No.</th>
					<th>Track Title</th>
					<th>Duration</th>
				</tr>
			</thead>
			<tbody>
				{%for track in record.track_set.all%}
				<tr>
					<td>{{track.track_no}}</td>
					<td>{{track.title}}</td>
					<td>{{track.duration}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		{% else %}
		<div>
      <p>No Tracks added</p>
		</div>
		{% endif %}
    <button id="track-add-btn">add track</button>
	</article>
</section>
{% endblock %}

main_app/templates/records/index.html
{% extends 'base.html' %} {% load static %} {% block head %} {% endblock %}
{%block content %}
<section class="page-header"></section>

<section class="card-container">
	{% for record in records %}
	<a href="{%url 'record-detail' record.id%}">
		<article class="card">
			<div class="card-content">
				<h3 class="card-title">{{ record.title }}</h2>
				<h4>{{record.artist}}</h3>
				<p>{{record.release_date}}</p>
			</div>
		</article>
	</a>
	{% endfor %}
</section>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}
<div class="page-header">
	<h1>Sign Up</h1>
</div>
{% if error_message %}
<p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}